apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-webhook
  namespace: whatsapp-webhook
  labels:
    app: whatsapp-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp-webhook
  template:
    metadata:
      labels:
        app: whatsapp-webhook
    spec:
      containers:
      - name: whatsapp-webhook
        image: cristianopluggerbi/whatsapp-webhook:latest
        ports:
        - containerPort: 5000
        env:
        - name: WEBHOOK_VERIFY_TOKEN
          valueFrom:
            secretKeyRef:
              name: whatsapp-webhook-secret
              key: WEBHOOK_VERIFY_TOKEN
        - name: DEBUG
          value: "False"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "5000"
        - name: LOG_LEVEL
          value: "INFO"
        - name: USE_SSL
          value: "False"
        - name: DB_HOST
          value: "168.75.106.98"
        - name: DB_PORT
          value: "6446"
        - name: DB_NAME
          value: "atendimento"
        - name: DB_USER
          value: "atendimento"
        - name: DB_PASSWORD
          value: "8/vLQv98vCmw%Ox1"
        - name: DB_ENABLED
          value: "True"
        - name: RABBITMQ_ENABLED
          value: "True"
        - name: RABBITMQ_HOST
          value: "rabbitmq-service.whatsapp-webhook.svc.cluster.local"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "admin"
        - name: RABBITMQ_PASSWORD
          value: "rabbitmq123"
        workingDir: /app
        command: ["python"]
        args: ["app.py"]
        resources:
          requests:
            memory: "32Mi"
            cpu: "20m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
      - name: frontend-config
        configMap:
          name: whatsapp-webhook-config
          items:
          - key: index.html
            path: index.html