// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohnqbjeopvcpybptkszl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9obnFiamVvcHZjcHlicHRrc3psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTI2NjcsImV4cCI6MjA2NzcyODY2N30.qsP5a5cSQU8KaieWoNIRx-Ccai40SC1buTCOvJB3WIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});